// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hobufehtjmhdurffmrbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYnVmZWh0am1oZHVyZmZtcmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzY1NTcsImV4cCI6MjA3MjIxMjU1N30.hO7aj1bvSgYyG7tOTWxmhgGZu91W3AO4zyvr0IRs01o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});